config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :photo
	
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	around_action :switch_locale

	def switch_locale(&action)
		I18n.with_locale(locale_from_header, &action)
	end

	private

	def locale_from_header
		request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      redirect_to categories_url, notice: t('.destroyed')
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  
  def index
    @products = Product.all.with_attached_photo
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_url(@product), notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    
    redirect_to products_path, notice: t('.destroyed') , status: :see_other
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :price, :description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
  <%= link_to t('.edit'), edit_category_path(category) %>
  <%= link_to t('.delete'), category_path(category), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') } %>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div id="categories">
  <%= render partial: 'category', collection: @categories %>
</div>

<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
	
	<% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    
  </div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
	<div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>
	<h2><%= product.title %></h2>
<% end %>

<%= image_tag product.photo, width: 200 if product.photo.attached? %>
<p><%= product.description %></p>
<span><%= product.price %></span>

app/views/products/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", product: @product %>

<br>

<div>
	<%= link_to "Ver producto", @product %>
	<%= link_to "Regresar a los productos", products_path %>
</div>

app/views/products/index.html.erb
<h1><%= t('.title') %></h1>

<div id="productos">
	<%= render partial: 'product', collection: @products %>
</div>

app/views/products/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", product: @product %>
<%= link_to "Regresar a los productos", products_path %>

app/views/products/show.html.erb
 <div id="<%= dom_id @product %>">

   <%= image_tag @product.photo, width: 200 if @product.photo.attached? %>
 	<p>
    <strong>Producto:</strong>
    <%= @product.title %>
  </p>
  <p>
     <%= @product.description %>
  </p>

  <div>
  	<%= link_to "Editar producto", edit_product_path(@product) %>

  	<%= link_to "Eliminar producto", product_path(@product), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') } %>
  	
  	<%= link_to "Regresar a los productos", products_path %>
  </div>


 </div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
	<h1>Choping cart</h1>
<% end %>

<%= link_to t('.add'), new_product_path %>
<%= link_to t('.categories'), categories_path %>